### ISSUE TITLE
Unicode Decode Error

### ISSUE THREAD

**Issue by nigelainscoe** [sixty-north/python-camtasia#12]
I thought this might save me some work with a bunch of Camtasia projects where I need to move the files around and rename some of them. I had the idea of using the project to discover the files, move them ant then update the file and timeline references. Unfortunately, opening the project gives the following:

I think the self._data = json.loads(self._project_file.read_text()) line probably needs encoding=utf-8 in it. I'll try and fix it but thought you might like to know.

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-10-bb41d7946f41> in <module>
----> 1 proj = camtasia.load_project('E:/Dev/Source/camtasia/Module One 5 Part Five')

~\Anaconda3\lib\site-packages\camtasia\project.py in load_project(file_path)
     69     """
     70     file_path = Path(file_path).resolve()
---> 71     return Project(file_path)
     72 
     73 

~\Anaconda3\lib\site-packages\camtasia\project.py in __init__(self, file_path)
     22     def __init__(self, file_path):
     23         self._file_path = file_path
---> 24         self._data = json.loads(self._project_file.read_text())
     25 
     26     @property

~\Anaconda3\lib\pathlib.py in read_text(self, encoding, errors)
   1198         """
   1199         with self.open(mode='r', encoding=encoding, errors=errors) as f:
-> 1200             return f.read()
   1201 
   1202     def write_bytes(self, data):

~\Anaconda3\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 22703: character maps to <undefined>

**Comment by nigelainscoe** [comment]
changing this in pathlib.py 

`        with self.open(mode='r', encoding=encoding, errors=errors) as f:
            return f.read()
`

to `        with self.open(mode='r', encoding='utf-8', errors=errors) as f:
            return f.read()
`

Seems to fix it but I suspect I shouldn't be modding pathlib.py 😀

**Comment by abingham** [comment]
Right, I'd steer clear of modifying pathlib :) Try making this change on project.py line 24:

```
self._data = json.loads(self.file_path.read_text(encoding='utf-8'))
```

I should almost certainly update `Project.__init__` and related functions to accept an `encoding` parameter.

**Comment by nigelainscoe** [comment]
Changing to this in project.py

`
    def __init__(self, file_path):
        self._file_path = file_path
        self._data = json.loads(self._project_file.read_text(encoding='utf-8'))
`

Seems to work. I've sent a patch.

The save function may need it. I'll see if I have problems doing a save() first though.

**Comment by nigelainscoe** [comment]
Ha, ha, you commented while I was doing exactly that 👍 

I'll get back to seeing if the package can do what I want 😁

**Comment by abingham** [comment]
I've just pushed an update that adds `encoding` to the `Project` initializer and related functions. I'll update `save` in a second.

**Comment by abingham** [comment]
Now it should be honoring the encoding on save as well (as of 6.1.1).

**Comment by abingham** [comment]
If the encoding stuff works for you, go ahead and close this out. Thanks for taking the time to report this!

**Comment by nigelainscoe** [comment]
And thanks!
